voterewards:
  keys:  
     unturnedServersApiKey: insert key
     unturnedSlApiKey: insert key
  rewards:
    - type: RewardType.Permission
      apiType: ClientType.Both
      name: mypermission.ok
      
      
    